Repository rwjblue/create-rwjblue-release-it-setup, pull requests merged in 2020-03, with the labels that each got.

#17 Ensure label sync uses same token as release-it and lerna-changelog.
  bin/rwjblue-release-it-setup.js
Labels: enhancement

#18 Update dependencies / devDependencies to latest.
  package.json
  yarn.lock
Labels: enhancement

#27 Ensure generated devDependencies match those used for testing.
  bin/rwjblue-release-it-setup.js
  tests/bin-test.js
Labels: enhancement

#28 Enable `release-it-lerna-changelog`s `launchEditor` feature.
  RELEASE.md
  bin/rwjblue-release-it-setup.js
  tests/bin-test.js
Labels: enhancement

#30 Ensure release-template.md is published with the project.
  package.json
Labels: bug

#35 Avoid deleting existing GitHub labels when adding new ones.
  bin/rwjblue-release-it-setup.js
Labels: bug

#36 Avoid downgrading release-it / release-it-lerna-changelog.
  bin/rwjblue-release-it-setup.js
  package.json
  tests/bin-test.js
  yarn.lock
Labels: bug

#37 Ensure existing `release-it` config is preserved.
  bin/rwjblue-release-it-setup.js
  tests/bin-test.js
Labels: bug

#38 Update release-it-lerna-changelog minimum version.
  package.json
  yarn.lock
Labels: enhancement

#42 Fixes bug in logic with --labels-only
  bin/rwjblue-release-it-setup.js
Labels: bug

#43 Update prettier to 2.0.
  package.json
  tests/bin-test.js
  yarn.lock
Labels: internal

#48 Add release-it-yarn-workspaces when workspaces are setup.
  bin/rwjblue-release-it-setup.js
  package.json
  tests/bin-test.js
  yarn.lock
Labels: enhancement

#51 Update release-it-yarn-workspaces to prompt for access control with scoped packages (if needed).
  package.json
  yarn.lock
Labels: enhancement

#52 Add release-it config to disable npm for private packages.
  bin/rwjblue-release-it-setup.js
  tests/bin-test.js
Labels: enhancement
